kind: ConfigMap
apiVersion: v1
spec:
 project: default
metadata:
  name: nginx-config
  namespace: sysadmin-nginx
data:
  proxy-connect-timeout: "10s"
  proxy-read-timeout: "10s"
  client-max-body-size: "2m"
